# Generated by Django 5.0.3 on 2024-04-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_porticos', '0002_listanegra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='listanegra',
            name='ciudad',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
