# Generated by Django 5.0.3 on 2024-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_porticos', '0004_alerta_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
