# Generated by Django 5.0.3 on 2024-04-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_porticos', '0005_alerta_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadVecina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='aplicacion_porticos.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='aplicacion_porticos.ciudad')),
            ],
        ),
    ]
