# Generated by Django 5.0.3 on 2024-04-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_porticos', '0006_ciudadvecina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='estado',
        ),
    ]
