"""
Django settings for porticos project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ntp(cq5m4@fduhipgm(nnx!&mt0_g7$+23viv7^2zevorxn$hk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['18.228.92.158', '127.0.0.1', 'localhost', 'teraflex.cl']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aplicacion_porticos',
    'corsheaders',
    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Mover el middleware de CORS aquí
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'porticos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'porticos.wsgi.application'
ASGI_APPLICATION = 'porticos.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'porticos2',
        'USER': 'admin',
        'PASSWORD': 'Teraf2022.',
        'HOST': 'porticos.chger7ymel2m.sa-east-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            'use_unicode': True,
            'isolation_level': 'repeatable read',  # Adjust isolation level as needed
        },
        'CONN_MAX_AGE': 1,  # Adjust connection age as needed
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UCT'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

APPEND_SLASH = False

# Configuración SSL
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True

CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = False

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

# Duración de la sesión en segundos (por defecto: 1209600 segundos = 2 semanas)
SESSION_COOKIE_AGE = 3600  # Duración de la sesión en segundos (1 hora)

# Nombre de la cookie de sesión (por defecto: 'sessionid')
SESSION_COOKIE_NAME = 'misesion'

# Dominio al que la cookie de sesión se aplicará (por defecto: None)
# SESSION_COOKIE_DOMAIN = '.example.com'  # Esto permitiría que la cookie sea enviada a todos los subdominios de example.com

# Camino en el servidor al que la cookie de sesión será válida (por defecto: '/')
SESSION_COOKIE_PATH = '/'

# Marca la cookie de sesión como segura (por defecto: False)
SESSION_COOKIE_SECURE = True

# Configura la marca HttpOnly para la cookie de sesión (por defecto: True)
SESSION_COOKIE_HTTPONLY = False

# Configura la marca SameSite para la cookie de sesión (por defecto: 'Lax')
SESSION_COOKIE_SAMESITE = 'None'  # Opciones: 'Strict', 'Lax', 'None'

# Configura el dominio en el que la cookie de sesión es válida (por defecto: None)
# SESSION_COOKIE_DOMAIN = 'example.com'

# Configura la política de expiración de la cookie de sesión (por defecto: 'None')
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False